name: Documentation
description: Report missing, unclear, or outdated documentation.
title: "[DOCS]: "
labels: documentation
assignees: ryanhlewis

body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve the project's documentation. 

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What is unclear, missing, incorrect, or outdated?
      placeholder: "Example: The installation steps are outdated and ..."
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Proposed Fix (Optional)
      description: Suggest wording, corrections, or structural improvements.
      placeholder: "Example: Replace the installation section with a more updated one referencing ..."

