name: VoxelEarth
version: 1.0
main: com.example.voxelearth.VoxelEarth
api-version: 1.20
description: A custom world generator plugin
author: Ryan Hardesty Lewis
load: STARTUP
softdepend:
  - FastAsyncWorldEdit
  - WorldEdit
commands:
  createcustomworld:
    description: Create a custom world with VoxelEarth generator.
    usage: /createcustomworld <worldname>
    permission: voxelearth.createcustomworld
    permission-message: You don't have permission to create a custom world.
  regenchunks:
    description: Regenerate chunks with new scale and offsets.
    usage: /regenchunks <scaleX> <scaleY> <scaleZ> <offsetX> <offsetY> <offsetZ>
    permission: voxelearth.regenchunks
    permission-message: You don't have permission to regenerate chunks.
  loadjson:
    description: Load a JSON file and apply scaling and offset.
    usage: /loadjson <filename> <scaleX> <scaleY> <scaleZ> <offsetX> <offsetY> <offsetZ>
    permission: voxelearth.loadjson
    permission-message: You don't have permission to load JSON files.
  voxelapikey:
    description: Store a custom Google API key for geocoding and tiles.
    usage: /voxelapikey <google-api-key>
    permission: voxelearth.apikey
    permission-message: You don't have permission to set the API key.
  visit:
    description: Teleport to a city or location using geocoding.
    usage: /visit <location>
    permission: voxelearth.visit
    permission-message: You don't have permission to use the visit command.
  visitradius:
    description: Set how many tiles /visit loads around the target
    usage: /visitradius <tiles>
    permission: voxelearth.settings
    permission-message: You don't have permission to set the visit radius.
  moveradius:
    description: Set how many tiles movement-triggered loads will fetch
    usage: /moveradius <tiles>
    permission: voxelearth.settings
    permission-message: You don't have permission to set the move radius.
  movethreshold:
    description: Set the movement distance threshold (in blocks) for triggering loads
    usage: /movethreshold <blocks>
    permission: voxelearth.settings
    permission-message: You don't have permission to set the move threshold.
  moveload:
    description: Toggle movement-based loading for yourself
    usage: /moveload <on|off|toggle|status>
    permission: voxelearth.moveload
    permission-message: You don't have permission to toggle moveload.
  moveloadother:
    description: Modify another player's movement-based loading preference
    usage: /moveloadother <player> [on|off|toggle|status]
    permission: voxelearth.moveload.other
    permission-message: You don't have permission to change other players' moveload status.
  visitradiusother:
    description: Set the visit radius while notifying another player
    usage: /visitradiusother <player> <tiles>
    permission: voxelearth.settings.other
    permission-message: You don't have permission to change the visit radius for others.
  moveradiusother:
    description: Set the movement load radius while notifying another player
    usage: /moveradiusother <player> <tiles>
    permission: voxelearth.settings.other
    permission-message: You don't have permission to change the move radius for others.
  movethresholdother:
    description: Set the movement threshold while notifying another player
    usage: /movethresholdother <player> <blocks>
    permission: voxelearth.settings.other
    permission-message: You don't have permission to change the move threshold for others.
  visitother:
    description: Teleport another player to a geocoded location
    usage: /visitother <player> <location>
    permission: voxelearth.visitother
    permission-message: You don't have permission to use /visitother
permissions:
  voxelearth.createcustomworld:
    description: Allows creating custom worlds with VoxelEarth.
    default: op
  voxelearth.regenchunks:
    description: Allows regenerating chunks with custom settings.
    default: op
  voxelearth.loadjson:
    description: Allows loading and applying JSON files.
    default: op
  voxelearth.apikey:
    description: Allows setting the custom Google API key for geocoding and tile downloads.
    default: true
  voxelearth.visit:
    description: Allows teleporting to a location using geocoding.
    default: true
  voxelearth.settings:
    description: Allows adjusting visit radius and movement settings.
    default: true
  voxelearth.admin:
    description: Allows setting visit radius and admin actions
    default: op
  voxelearth.visitother:
    description: Allows teleporting another player to a geocoded location
    default: op
  voxelearth.moveload:
    description: Allows toggling personal MoveLoad status
    default: true
  voxelearth.moveload.other:
    description: Allows changing MoveLoad status for other players
    default: op
  voxelearth.settings.other:
    description: Allows changing visit/move settings and notifying other players
    default: op
