name: VoxelEarth
version: 1.0
main: com.example.voxelearth.VoxelEarth
api-version: 1.20
description: A custom world generator plugin
author: YourName
load: STARTUP
commands:
  createcustomworld:
    description: Create a custom world with VoxelEarth generator
    usage: /createcustomworld <worldname>
  regenchunks:
    description: Regenerate chunks with new scale and offsets.
    usage: /regenchunks <scale> <offsetX> <offsetY> <offsetZ>
  loadjson:
    description: Load a JSON file and apply scaling and offset.
    usage: /loadjson <filename> <scaleX> <scaleY> <scaleZ> <offsetX> <offsetY> <offsetZ>