name: VoxelEarth
version: 1.0
main: com.example.voxelearth.VoxelEarth
api-version: 1.20
description: A custom world generator plugin
author: YourName
load: STARTUP
commands:
  createcustomworld:
    description: Create a custom world with VoxelEarth generator.
    usage: /createcustomworld <worldname>
    permission: voxelearth.createcustomworld
    permission-message: You don't have permission to create a custom world.
  regenchunks:
    description: Regenerate chunks with new scale and offsets.
    usage: /regenchunks <scaleX> <scaleY> <scaleZ> <offsetX> <offsetY> <offsetZ>
    permission: voxelearth.regenchunks
    permission-message: You don't have permission to regenerate chunks.
  loadjson:
    description: Load a JSON file and apply scaling and offset.
    usage: /loadjson <filename> <scaleX> <scaleY> <scaleZ> <offsetX> <offsetY> <offsetZ>
    permission: voxelearth.loadjson
    permission-message: You don't have permission to load JSON files.
  visit:
    description: Teleport to a city or location using geocoding.
    usage: /visit <location>
    permission: voxelearth.visit
    permission-message: You don't have permission to use the visit command.
permissions:
  voxelearth.createcustomworld:
    description: Allows creating custom worlds with VoxelEarth.
    default: op
  voxelearth.regenchunks:
    description: Allows regenerating chunks with custom settings.
    default: op
  voxelearth.loadjson:
    description: Allows loading and applying JSON files.
    default: op
  voxelearth.visit:
    description: Allows teleporting to a location using geocoding.
    default: true